### ISSUE TITLE
Failed to compile shader

### ISSUE THREAD

**Issue by sg3des** [tbogdala/fizzle#1]
```
Failed to compile and link the diffuse shader program!
Failed to compile the fragment shader:
0:37(24): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later
```

This error occurs when run **lights_forward**, building goes well.

if in shader [diffuse_texbumped_shadows](https://github.com/tbogdala/fizzle/blob/master/examples/assets/forwardshaders/diffuse_texbumped_shadows.fs) replace loop with _shadow_i_ on manually index all running...

```
for (int shadow_i=0; shadow_i<SHADOW_COUNT; shadow_i++) {
    shadow += textureProj(SHADOW_MAPS[i], vs_shadow_coord[i]);
}
```

```
shadow += textureProj(SHADOW_MAPS[0], vs_shadow_coord[0]);
shadow += textureProj(SHADOW_MAPS[1], vs_shadow_coord[1]);
shadow += textureProj(SHADOW_MAPS[2], vs_shadow_coord[2]);
shadow += textureProj(SHADOW_MAPS[3], vs_shadow_coord[3]);
```

**Comment by tbogdala** [comment]
I think this was working on Windows with NVidia drivers because I haven't changed these shaders in a while and I frequently run this sample.

However, I did reproduce this on Linux with the Nouveau drivers.

**Comment by tbogdala** [comment]
Thanks for the report and the solution tip. I enclosed them in `if` blocks so the scaling of the shadow value happens correctly.

These shaders are all in kind of a sad state. I have some prototype projects with better ADS lighting functions but haven't brought  them into the core yet.
