### ISSUE TITLE
Dynamically create new objects

### ISSUE THREAD

**Issue by sg3des** [tbogdala/fizzle#3]
Hello. 

I have a some problem with create new objects after initialize window, render etc... what am I doing wrong?

Also, in your example [cube](https://github.com/tbogdala/fizzle/blob/master/examples/cube.go), you previously create sphere and cube, and then just swap its.

**Comment by tbogdala** [comment]
I would need an error message or a better description of what the problem is. It's too vague right now.

**Comment by sg3des** [comment]
i`m found a root of problem - if load shader before loop then all ok, else if load shader after initialize, then new object not displayed.
[example](https://github.com/sg3des/fizzle-example)

**Comment by sg3des** [comment]
Now, when the cause of the problem is understandable, it does not look so critical, all shaders can be pre uploaded.
maybe mark this in comments at code?

**Comment by tbogdala** [comment]
Sorry it took me a while to get to this. Can you point to where the problem is in the example code you referenced, or have you figured it out now?

**Comment by sg3des** [comment]
Sorry I have replaced this example...  however problem is solved - all used shaders must be proloaded.
